name: Deploy CloudMediaHub to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        working-directory: MediaAPI
        run: npm install

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_43FE7755EA324ABBA40EF6F4F51507A2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5894FC6A22CB4C5385178B7008E26DCD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6D6F53809E3D4B0CB51EA574AD16D560 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'cmh-funcapp-9872'
          package: 'MediaAPI'
